version: "3.9"

services:
  api_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: api_backend

    environment:
      OPENAI_API_KEY: "klucz"
      CHROMA_COLLECTION_NAME: "talenrApp"
      CHROMA_DIR: "data/chroma"

    volumes:
      - ./data:/app/data
