version: "3.9"

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j-db

    ports:
      - "7474:7474"
      - "7687:7687"

    environment:
      NEO4J_AUTH: neo4j/test1234

      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"

      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"

    volumes:
      - ./data/db:/data
      - ./data/logs:/logs
      - ./data/plugins:/plugins